### ISSUE TITLE
Production build has rollup syntax error

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-plugin-msaview#36]
Probably from changing output to do esnext in react-msaview

The line referred to SyntaxError: Unexpected token (443:24) in /home/cdiesh/src/jbrowse-plugin-msaview/node_modules/react-msaview/dist/model.js has a nullish coalesceing operator. can either transpile down react-msaview code to lower es version or fix it here

```
yarn run v1.22.21
$ npm run clean

> jbrowse-plugin-msaview@1.0.18 clean
> rimraf dist

$ rollup --config --bundleConfigAsCjs

/home/cdiesh/src/jbrowse-plugin-msaview/src/index.ts → dist/jbrowse-plugin-msaview.umd.development.js, dist/jbrowse-plugin-msaview.umd.production.min.js...
[!] (plugin at position 6) SyntaxError: Unexpected token (443:24) in /home/cdiesh/src/jbrowse-plugin-msaview/node_modules/react-msaview/dist/model.js
node_modules/react-msaview/dist/model.js (443:24)
    at Parser.pp$4.raise (/home/cdiesh/src/jbrowse-plugin-msaview/node_modules/rollup-plugin-node-globals/node_modules/acorn/dist/acorn.js:2757:13)
    at Parser.pp.unexpected (/home/cdiesh/src/jbrowse-plugin-msaview/node_modules/rollup-plugin-node-globals/node_modules/acorn/dist/acorn.js:647:8)
    at Parser.pp$3.parseExprAtom (/home/cdiesh/src/jbrowse-plugin-msaview/node_modules/rollup-plugin-node-globals/node_modules/acorn/dist/acorn.js:2196:10)
    at Parser.pp$3.parseExprSubscripts (/home/cdiesh/src/jbrowse-plugin-msaview/node_modules/rollup-plugin-node-globals/node_modules/acorn/dist/acorn.js:2047:19)
    at Parser.pp$3.parseMaybeUnary (/home/cdiesh/src/jbrowse-plugin-msaview/node_modules/rollup-plugin-node-globals/node_modules/acorn/dist/acorn.js:2024:17)
    at Parser.pp$3.parseExprOps (/home/cdiesh/src/jbrowse-plugin-msaview/node_modules/rollup-plugin-node-globals/node_modules/acorn/dist/acorn.js:1966:19)
    at Parser.pp$3.parseMaybeConditional (/home/cdiesh/src/jbrowse-plugin-msaview/node_modules/rollup-plugin-node-globals/node_modules/acorn/dist/acorn.js:1949:19)
    at Parser.pp$3.parseMaybeAssign (/home/cdiesh/src/jbrowse-plugin-msaview/node_modules/rollup-plugin-node-globals/node_modules/acorn/dist/acorn.js:1925:19)
    at Parser.pp$3.parseMaybeConditional (/home/cdiesh/src/jbrowse-plugin-msaview/node_modules/rollup-plugin-node-globals/node_modules/acorn/dist/acorn.js:1954:28)
    at Parser.pp$3.parseMaybeAssign (/home/cdiesh/src/jbrowse-plugin-msaview/node_modules/rollup-plugin-node-globals/node_modules/acorn/dist/acorn.js:1925:19)


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by cmdcolin** [comment]
fixed by https://github.com/GMOD/jbrowse-plugin-msaview/pull/37
